#!/bin/bash

if [ -z "$1" ]
then
	echo "Please specify key filename"
	exit 1
fi

if [ -e "$HOME/.ssh/$1" ] && [ -e "$HOME/.ssh/$1.pub" ]
then
 	cp "$HOME/.ssh/$1" "$HOME/.ssh/id_rsa"
	cp "$HOME/.ssh/$1.pub" "$HOME/.ssh/id_rsa.pub"
	echo "Switched to ssh key $1"
	exit 0
else
	echo "Key files not found for $1"
	exit 1
fi

